### ISSUE TITLE
Implement Table list of Memes the user owns (desc)

### ISSUE THREAD

**Issue by bragadino** [mohamedhayibor/ethervineAlpha#11]
* https://getbootstrap.com/docs/4.1/content/tables/#table-head-options
* https://getbootstrap.com/docs/4.1/content/tables/#hoverable-rows

> Table pops out only when asked for it. (click on button)

**Comment by mohamedhayibor** [comment]
7a7ecb28d6db1443b4f5f1c2b4baca0c5a10bb31
